### ISSUE TITLE
Drawing a line show Dot in touch begin point

### ISSUE THREAD

**Issue by ChanchalW** [Awalz/SwiftyDraw#16]
When you fast drag on screen it draws the line on point captured in 'Touch Begin' and then continue new line touch move points. 

Screenshot 
![img_1393](https://user-images.githubusercontent.com/21195828/50472446-d7d59800-09de-11e9-8509-ac873e644934.PNG)

**Comment by LinusGeffarth** [comment]
Thanks for the submission. This is actually a known bug related to enabling and disabling the draw view dynamically.

Do you use the delegate methods?

**Comment by ChanchalW** [comment]
Wow, really fast reply.
I am not enabling/disabling draw. I am just using draw start with view controller. 
I am not using delegate methods.

**Comment by LinusGeffarth** [comment]
Are you seeing the same issue in the example project?

**Comment by ChanchalW** [comment]
Ok, Great work.
Thank You again.

**Comment by ChanchalW** [comment]
Any update on this?

**Comment by LinusGeffarth** [comment]
@ChanchalW not so far, no. I'm short on time these days... Have you tried investigating in the library yourself?

**Comment by klinkert0728** [comment]
Hey @ChanchalW I am having the same issue, were you able to find a solution or workaround, so it happens to me when the drawing area is inside a scrollView.

**Comment by klinkert0728** [comment]
@LinusGeffarth  I was able to check the library and identify the issue.
I was able to replicate this issue in the demo project basically by drawing from left to right quickly.

The issue is related with the paths that are created when the method `touchesBegan` is being call and when the `touchesMoved` gets called.

basically in the images attached you can see that the position for the x is different so that makes this little white area appear

![Screenshot 2019-10-31 at 15 46 45](https://user-images.githubusercontent.com/6820828/67957655-39b1f000-fbf6-11e9-8aaa-1a0785f7974b.png)
![Screenshot 2019-10-31 at 15 49 37](https://user-images.githubusercontent.com/6820828/67957657-39b1f000-fbf6-11e9-8a9a-0776a2769696.png)

hope this can help to fix the issue :)

**Comment by klinkert0728** [comment]
Can we expect a new version with the fix ? @LinusGeffarth thanks for the quick reply 👍

**Comment by LinusGeffarth** [comment]
That would be cool, indeed, but I'm _really_ busy these days. If you could propose a PR, that'd definitely speed it up.
(Although I'm guilty for not having checked the last one yet 😬)

**Comment by klinkert0728** [comment]
lol :) .  I will try to make it work and have a PR during the weekend :) thanks

**Comment by klinkert0728** [comment]
Hey @LinusGeffarth  check this PR actually I think the fix was pretty simple let me know if for some reason breaks another feature I tried but everything seems to be working as expected with the change. Please let me know https://github.com/Awalz/SwiftyDraw/pull/29

**Comment by klinkert0728** [comment]
Hey @LinusGeffarth  can you generate a new release for the pod :) thank you

**Comment by LinusGeffarth** [comment]
Yes, give me a minute

**Comment by klinkert0728** [comment]
hey @LinusGeffarth  is the latest version available in pod? I am still getting the. `2.1.5`

**Comment by LinusGeffarth** [comment]
No not yet, I was having issues with CocoaPods...

**Comment by LinusGeffarth** [comment]
Ok, published. Try again now @klinkert0728

**Comment by klinkert0728** [comment]
got it thank you 👍
