### ISSUE TITLE
Can you add text onto the picture as well as drawing on it?

### ISSUE THREAD

**Issue by derens99** [Awalz/SwiftyDraw#17]

**Comment by LinusGeffarth** [comment]
Hey! Thanks for the suggestion. In an app of mine, I've implemented just that feature. I've thought about adding it to the library itself but concluded this is out the main scope.

**Comment by LinusGeffarth** [comment]
Sorry for the delay. So the logic is that you have to create a draggable view class (using a gesture recognizer), and then subclass labels, images, etc. from that. To add them to the draw view, simply do `drawView.addSubview(<view>)` just like you'd add any other view.
You'd also have to handle tapping the views. In that case you should display like handles, or something and make it draggable, so that the user can change its position.

**Comment by derens99** [comment]
Ah great! Thank you much appreciated.
