### ISSUE TITLE
Carthage Installation Support

### ISSUE THREAD

**Issue by fanquake** [Awalz/SwiftyDraw#8]
It'd be great to be able to install SwiftyDraw via [Carthage](https://github.com/Carthage/Carthage). They have some notes on adding Carthage support to a framework [here](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework).

I might have a go at implementing this myself over the next few days, but wanted to open an issue to track any discussion/thoughts.

**Comment by LinusGeffarth** [comment]
Hey @fanquake, I've never worked with Carthage before. If you'd like to, please do add the project there.
Please submit a pull request for the readme describing how to install the library using Carthage.

**Comment by msztech** [comment]
@LinusGeffarth Mind if I work on this issue and PR?

**Comment by msztech** [comment]
@LinusGeffarth PR submitted. I have tried on my local machine.

You can also try to add the framework from Carthage. Since Carthage fetches from the Github, you can try to fetch from my fork by adding the following line in your `Cartfile`

`github "msztech/SwiftyDraw" "master"`

Carthage, comparing to pod, is a little bit complex to set up. You can refer to [official README](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) to try set it up. Basically, it builds the codes from the `master` into a framework.

;-)
